#Database credentials

database:
  type: "sqlite" #sqlite or mysql
  host: "localhost"
  port: "3306"
  dbname: "kitdatabase"
  username: "username"
  password: "pa55w0rd"

publickits:
 # 1:
 #   name: "Kit 1"
 #   icon: "DIAMOND_SWORD"
