#Database credentials

database:
  type: "sqlite" #sqlite or mysql
  host: "localhost"
  port: "3306"
  dbname: "kitdatabase"
  username: "username"
  password: "pa55w0rd"

motd:
  enabled: false
  delay: 5
  message: #join messages using mini message format
    - "<green>--------------------- <white>Per Player Kits <green>---------------------"
    - "<blue>Type <white>/kit <blue> or <white>/k <blue>to get started!"
    - "<green>------------------------------------------------------------------"

scheduled-broadcast: #uses mini message format
  enabled: false
  period: 900 #in seconds
  messages:
    - "<green>Kit <white>{kit} <green>was just redeemed by <white>{player}!"


kitroom:
  items:
    1:
      name: "OG Vanilla"
      material: "DIAMOND_SWORD"
    2:
      name: "Training"
      material: "WOODEN_SWORD"
    3:
        name: "Potions"
        material: "SPLASH_POTION"
    4:
        name: "Armory"
        material: "NETHERITE_SWORD"
    5:
        name: "Axe & UHC"
        material: "SHIELD"

disabled-command-worlds:
  - "example_world"

disabled-command-message: "&cKits are disabled here!"


publickits:
 # 1:
 #   name: "Kit 1"
 #   icon: "DIAMOND_SWORD"
