#Database credentials

database:
  type: "sqlite" #sqlite or mysql
  host: "localhost"
  port: "3306"
  dbname: "kitdatabase"
  username: "username"
  password: "pa55w0rd"

motd:
  enabled: true
  delay: 5
  message: #join messages using mini message format
    - ""
    - "<gray>   <st>                </st> <aqua><b>Per Player Kits</b><gray> <st>                </st>"
    - ""
    - "         <white>Type <aqua>/kit<white>, <aqua>/k <white>or <aqua>/pk<white> to get started!"
    - ""
    - "<gray>   <st>                                                         "
    - ""

scheduled-broadcast: #uses mini message format
  enabled: true
  period: 900 #in seconds
  messages:
    - ""
    - "<gray>   <st>                                                         "
    - ""
    - "         <white>Type <aqua>/kit<white>, <aqua>/k <white>or <aqua>/pk<white> to get started!"
    - ""
    - "<gray>   <st>                                                         "
    - ""


kitroom:
  items:
    1:
      name: "OG Vanilla"
      material: "DIAMOND_SWORD"
    2:
      name: "Training"
      material: "WOODEN_SWORD"
    3:
        name: "Potions"
        material: "SPLASH_POTION"
    4:
        name: "Armory"
        material: "NETHERITE_SWORD"
    5:
        name: "Axe & UHC"
        material: "SHIELD"

disabled-command-worlds:
  - "example_world"

disabled-command-message: "&cKits are disabled here!"


publickits:
  1:
    name: "Kit 1"
    icon: "DIAMOND_SWORD"
