name: PerPlayerKit
version: "${project.version}"
main: dev.noah.perplayerkit.PerPlayerKit
author: Noah Ross
api-version: 1.19
commands:

  aboutperplayerkit:
    usage: /<command>
    default: true

  kitroom:
    usage: /<command>
    permission: kit.admin

  kit:
    usage: /<command>
    permission: kit.use
    aliases: k

  copykit:
    usage: /<command>
    permission: kit.use
    aliases:
      - copyec
      - copyenderchest

  sharekit:
    usage: /<command>
    permission: kit.use

  shareec:
    usage: /<command>
    permission: kit.use
    aliases:
      - shareenderchest

  swapkit:
    usage: /<command>
    permission: kit.use

  deletekit:
    usage: /<command>
    permission: kit.use

  inspectkit:
    usage: /<command>
    permission: kit.staff

  publickit:
    aliases:
      - pk
      - premadekit
    usage: /<command>
    permission: kit.use

  k1:
    usage: /<command>
    permission: kit.use
    aliases: kit1
  k2:
    usage: /<command>
    permission: kit.use
    aliases: kit2
  k3:
    usage: /<command>
    permission: kit.use
    aliases: kit3
  k4:
    usage: /<command>
    permission: kit.use
    aliases: kit4
  k5:
    usage: /<command>
    permission: kit.use
    aliases: kit5
  k6:
    usage: /<command>
    permission: kit.use
    aliases: kit6
  k7:
    usage: /<command>
    permission: kit.use
    aliases: kit7
  k8:
    usage: /<command>
    permission: kit.use
    aliases: kit8
  k9:
    usage: /<command>
    permission: kit.use
    aliases: kit9

  ec1:
    usage: /<command>
    permission: kit.enderchest
    aliases: enderchest1
  ec2:
    usage: /<command>
    permission: kit.enderchest
    aliases: enderchest2
  ec3:
    usage: /<command>
    permission: kit.enderchest
    aliases: enderchest3
  ec4:
    usage: /<command>
    permission: kit.enderchest
    aliases: enderchest4
  ec5:
    usage: /<command>
    permission: kit.enderchest
    aliases: enderchest5
  ec6:
    usage: /<command>
    permission: kit.enderchest
    aliases: enderchest6
  ec7:
    usage: /<command>
    permission: kit.enderchest
    aliases: enderchest7
  ec8:
    usage: /<command>
    permission: kit.enderchest
    aliases: enderchest8
  ec9:
    usage: /<command>
    permission: kit.enderchest
    aliases: enderchest9

  enderchest:
    usage: /<command>
    permission: kit.enderchest
    aliases: ec

  savepublickit:
    usage: /<command> <id>
    permission: kit.admin

  regear:
    usage: /<command>
    permission: kit.use
    aliases:
      - rg
